### ISSUE TITLE
Newline at end of file should be optional?

### ISSUE THREAD

**Issue by qpkorr** [vanillaes/csv#16]
Hi - thanks for sharing your great CSV handling code.
One thing - I think the spec allows for not having a newline at the end of the file:
2.  The last record in the file may or may not have an ending line
       break.  For example:
       aaa,bbb,ccc CRLF
       zzz,yyy,xxx
but I don't think your code does yet. Hopefully easily fixed.

**Comment by evanplaice** [comment]
This is covered already. If you set the `eof` option to `false` the output won't have a newline at the end-of-file
