### ISSUE TITLE
Parse raises `CSVError: Illegal state` on comma in quoted field. (Not RFC compliant?)

### ISSUE THREAD

**Issue by lynnpepin** [vanillaes/csv#20]
Hi all! This is good work and I'm happy to find a pure-ES CSV parser.

I have some data I'm trying to parse, but it throws errors. Here is an example:

```
export var town06_csv = `
x,y,z,pitch,yaw,roll,formatted
586.8056030273438, -10.063207626342773, 0.29999998211860657, 0.0, -179.58056640625, 0.0, "[586.806, -10.063, 0.300, 0.000, -179.581, 0.000]"
584.8312377929688, -13.57775592803955, 0.29999998211860657, 0.0, -179.58056640625, 0.0, "[584.831, -13.578, 0.300, 0.000, -179.581, 0.000]"
`
```

Note the last entry is `"[586.806, -10.063, 0.300, 0.000, -179.581, 0.000]"`, i.e. a single entry enclosed in double quotes. I import this CSV string and the parser, and run `parse` like this:

```
<script type="module">
  import { town06_csv } from './raw_spawn_data.js';
  import { parse } from './escsv.js'
  var town06_spawnpoints = parse(town06_csv);
</script>
```

But we get an error `Uncaught Error: CSVError: Illegal state [row:3, col:7]`! Per RFC4180 ( https://www.rfc-editor.org/rfc/rfc4180#section-2 ), this should be allowed, because the field is enclosed by a double quote. As far as I can tell, there is no error in my CSV, and it parses correctly in other parsers, e.g. in OpenOffice:

![image](https://user-images.githubusercontent.com/19627675/168393459-b3179775-a6bc-48ae-8c8a-d280aeb76403.png)

Specifically, it throws the error on line 67 (case 2, un-delimited input, defaults to state 4.)

**Comment by tbjgolden** [comment]
I'll have a go at this

**Comment by tbjgolden** [comment]
Hi @lynnpepin 

Seems like this is because of this space:

```
, "[586.806, -10.063, 0.300, 0.000, -179.581, 0.000]"
```

Just looked at the EBNF of the spec and actually a space isn't allowed there.

Your expectation seems sensible though, and it seems is already being tracked with #12

**Comment by lynnpepin** [comment]
Hi, that explains it, thank you! I didn't even think of the whitespace. (Lucky me, I'm also the one generating the CSV, so it's my bug to fix... Humbling!) Given this is a dupe, I'll close with this comment. Thank you again!
